-- 1. Create subscription_plans table
CREATE TABLE IF NOT EXISTS subscription_plans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL, -- e.g., 'Pro Monthly', 'Pro Yearly'
    description TEXT,
    price DECIMAL(12, 2) NOT NULL,
    duration_days INTEGER NOT NULL, -- 30 for monthly, 365 for yearly
    features JSONB DEFAULT '[]', -- List of features
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default plans
INSERT INTO subscription_plans (name, description, price, duration_days, features) VALUES
('Pro Monthly', 'Akses penuh ke semua fitur selama 30 hari', 50000, 30, '["Unlimited Products", "Advanced Analytics", "Multi-user", "Priority Support"]'),
('Pro Yearly', 'Hemat 2 bulan dengan langganan tahunan', 500000, 365, '["Unlimited Products", "Advanced Analytics", "Multi-user", "Priority Support", "2 Months Free"]');

-- 2. Create subscription_transactions table
CREATE TABLE IF NOT EXISTS subscription_transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE NOT NULL,
    plan_id UUID REFERENCES subscription_plans(id),
    merchant_order_id TEXT NOT NULL UNIQUE, -- Generated by us (e.g., INV-TIMESTAMP-STOREID)
    reference_id TEXT, -- From Duitku
    amount DECIMAL(12, 2) NOT NULL,
    payment_method TEXT,
    payment_url TEXT,
    status TEXT DEFAULT 'pending', -- pending, success, failed, expired
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Update stores table to track subscription
ALTER TABLE stores 
ADD COLUMN IF NOT EXISTS subscription_plan_id UUID REFERENCES subscription_plans(id),
ADD COLUMN IF NOT EXISTS subscription_status TEXT DEFAULT 'demo', -- demo, active, expired
ADD COLUMN IF NOT EXISTS subscription_end_date TIMESTAMP WITH TIME ZONE;

-- 4. Enable RLS
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_transactions ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies

-- Plans: Everyone can read active plans
CREATE POLICY "Everyone can read active plans" 
ON subscription_plans FOR SELECT 
USING (is_active = true);

-- Transactions: Store owners can view their own transactions
CREATE POLICY "Store owners can view own transactions" 
ON subscription_transactions FOR SELECT 
TO authenticated
USING (
    store_id IN (
        SELECT store_id FROM store_members 
        WHERE user_id = auth.uid()
    )
);

-- Transactions: Only service role (Edge Function) can insert/update
-- Note: In Supabase, service role bypasses RLS, so we don't strictly need a policy for it,
-- but we need to ensure users CANNOT insert/update directly.
-- So we DO NOT create INSERT/UPDATE policies for authenticated users.

-- 6. Platform Admins can view all transactions
CREATE POLICY "Platform admins can view all transactions" 
ON subscription_transactions FOR SELECT 
TO authenticated
USING (
    auth.email() IN (SELECT email FROM platform_admins)
);
