// Supabase Database Types
// This file will be auto-generated by Supabase CLI after setup
// Run: supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      stores: {
        Row: {
          id: string
          name: string
          slug: string
          address: string | null
          phone: string | null
          logo_url: string | null
          qris_code: string | null
          cart_enabled: boolean
          plan: string
          plan_expires_at: string | null
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          address?: string | null
          phone?: string | null
          logo_url?: string | null
          qris_code?: string | null
          cart_enabled?: boolean
          plan?: string
          plan_expires_at?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          address?: string | null
          phone?: string | null
          logo_url?: string | null
          qris_code?: string | null
          cart_enabled?: boolean
          plan?: string
          plan_expires_at?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      store_members: {
        Row: {
          id: string
          store_id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          store_id: string
          user_id: string
          role?: string
          created_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
      }
      products: {
        Row: {
          id: string
          store_id: string
          name: string
          price: number
          cost: number
          image_url: string | null
          category: string | null
          description: string | null
          is_promo: boolean
          promo_price: number | null
          is_active: boolean
          is_best_seller: boolean
          total_stock: number
          min_stock_level: number
          qty_per_unit: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          name: string
          price: number
          cost?: number
          image_url?: string | null
          category?: string | null
          description?: string | null
          is_promo?: boolean
          promo_price?: number | null
          is_active?: boolean
          is_best_seller?: boolean
          total_stock?: number
          min_stock_level?: number
          qty_per_unit?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          name?: string
          price?: number
          cost?: number
          image_url?: string | null
          category?: string | null
          description?: string | null
          is_promo?: boolean
          promo_price?: number | null
          is_active?: boolean
          is_best_seller?: boolean
          total_stock?: number
          min_stock_level?: number
          qty_per_unit?: number
          created_at?: string
          updated_at?: string
        }
      }
      sales: {
        Row: {
          id: string
          store_id: string
          total: number
          profit: number
          sale_type: string
          notes: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          store_id: string
          total: number
          profit: number
          sale_type?: string
          notes?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          total?: number
          profit?: number
          sale_type?: string
          notes?: string | null
          created_by?: string | null
          created_at?: string
        }
      }
      sale_items: {
        Row: {
          id: string
          sale_id: string
          product_id: string
          product_name: string
          quantity: number
          price: number
          cost: number
        }
        Insert: {
          id?: string
          sale_id: string
          product_id: string
          product_name: string
          quantity: number
          price: number
          cost: number
        }
        Update: {
          id?: string
          sale_id?: string
          product_id?: string
          product_name?: string
          quantity?: number
          price?: number
          cost?: number
        }
      }
      purchases: {
        Row: {
          id: string
          store_id: string
          product_id: string
          product_name: string
          quantity: number
          unit_cost: number
          total_cost: number
          pack_quantity: number | null
          units_per_pack: number | null
          supplier_id: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          store_id: string
          product_id: string
          product_name: string
          quantity: number
          unit_cost: number
          total_cost: number
          pack_quantity?: number | null
          units_per_pack?: number | null
          supplier_id?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          product_id?: string
          product_name?: string
          quantity?: number
          unit_cost?: number
          total_cost?: number
          pack_quantity?: number | null
          units_per_pack?: number | null
          supplier_id?: string | null
          notes?: string | null
          created_at?: string
        }
      }
      stock_details: {
        Row: {
          id: string
          store_id: string
          product_id: string
          purchase_id: string | null
          quantity: number
          unit_cost: number
          created_at: string
        }
        Insert: {
          id?: string
          store_id: string
          product_id: string
          purchase_id?: string | null
          quantity: number
          unit_cost: number
          created_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          product_id?: string
          purchase_id?: string | null
          quantity?: number
          unit_cost?: number
          created_at?: string
        }
      }
      suppliers: {
        Row: {
          id: string
          store_id: string
          name: string
          contact_person: string | null
          phone: string | null
          address: string | null
          created_at: string
        }
        Insert: {
          id?: string
          store_id: string
          name: string
          contact_person?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          name?: string
          contact_person?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
        }
      }
      snack_requests: {
        Row: {
          id: string
          store_id: string
          product_id: string | null
          requester_name: string
          snack_name: string
          quantity: number
          notes: string | null
          request_type: string
          status: string
          is_read: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          product_id?: string | null
          requester_name: string
          snack_name: string
          quantity: number
          notes?: string | null
          request_type?: string
          status?: string
          is_read?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          product_id?: string | null
          requester_name?: string
          snack_name?: string
          quantity?: number
          notes?: string | null
          request_type?: string
          status?: string
          is_read?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      reconciliations: {
        Row: {
          id: string
          store_id: string
          date: string
          expected_cash: number
          actual_cash: number
          cash_difference: number
          stock_items: Json
          total_stock_value: number
          total_stock_cost: number
          unidentified_amount: number
          generated_sale_ids: string[]
          notes: string | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          store_id: string
          date: string
          expected_cash: number
          actual_cash: number
          cash_difference: number
          stock_items?: Json
          total_stock_value: number
          total_stock_cost: number
          unidentified_amount: number
          generated_sale_ids?: string[]
          notes?: string | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          date?: string
          expected_cash?: number
          actual_cash?: number
          cash_difference?: number
          stock_items?: Json
          total_stock_value?: number
          total_stock_cost?: number
          unidentified_amount?: number
          generated_sale_ids?: string[]
          notes?: string | null
          status?: string
          created_at?: string
        }
      }
      settings: {
        Row: {
          id: string
          store_id: string
          key: string
          value: string
        }
        Insert: {
          id?: string
          store_id: string
          key: string
          value: string
        }
        Update: {
          id?: string
          store_id?: string
          key?: string
          value?: string
        }
      }
      cron_logs: {
        Row: {
          id: string
          job_name: string
          status: string
          response_time_ms: number | null
          details: Json
          created_at: string
        }
        Insert: {
          id?: string
          job_name?: string
          status?: string
          response_time_ms?: number | null
          details?: Json
          created_at?: string
        }
        Update: {
          id?: string
          job_name?: string
          status?: string
          response_time_ms?: number | null
          details?: Json
          created_at?: string
        }
      }
      testimonials: {
        Row: {
          id: string
          name: string
          role: string
          quote: string
          initials: string
          color: string
          border_color: string
          is_active: boolean
          order_index: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          role: string
          quote: string
          initials?: string
          color?: string
          border_color?: string
          is_active?: boolean
          order_index?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          role?: string
          quote?: string
          initials?: string
          color?: string
          border_color?: string
          is_active?: boolean
          order_index?: number
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_store_ids: {
        Args: Record<PropertyKey, never>
        Returns: string[]
      }
      is_store_member: {
        Args: {
          check_store_id: string
        }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Insertable<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type Updatable<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Commonly used types
export type Store = Tables<'stores'>
export type StoreMember = Tables<'store_members'>
export type Product = Tables<'products'>
export type Sale = Tables<'sales'>
export type SaleItem = Tables<'sale_items'>
export type Purchase = Tables<'purchases'>
export type StockDetail = Tables<'stock_details'>
export type Supplier = Tables<'suppliers'>
export type SnackRequest = Tables<'snack_requests'>
export type Reconciliation = Tables<'reconciliations'>
export type Setting = Tables<'settings'>
export type CronLog = Tables<'cron_logs'>
export type Testimonial = Tables<'testimonials'>
