-- This script was generated by a tool. Please don't modify it directly.

-- Create an RPC to safely delete from auth.users (strictly for Admin use)
CREATE OR REPLACE FUNCTION public.admin_delete_auth_user(p_user_id UUID)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER -- Ensures the function runs with admin privileges (to access auth.users)
SET search_path = public
AS $$
DECLARE
  v_caller_email text;
  v_is_admin boolean;
BEGIN
  -- 1. Check if the caller is a platform admin
  -- First, get the caller's email from auth.users
  SELECT email INTO v_caller_email FROM auth.users WHERE id = auth.uid();

  -- Then check if this email is in the hardcoded list of admins or in platform_admins table
  SELECT EXISTS (
      SELECT 1 FROM platform_admins WHERE email = v_caller_email
      UNION
      SELECT 1 WHERE v_caller_email IN ('admin@rsquareidea.my.id', 'rickyrickoard@gmail.com')
  ) INTO v_is_admin;

  IF NOT v_is_admin THEN
      RETURN jsonb_build_object(
          'success', false,
          'message', 'Hanya Platform Admin yang dapat menghapus user secara permanen.'
      );
  END IF;

  -- 2. Delete the user
  -- The auth.users table is restricted. This SECURITY DEFINER function bypasses RLS
  DELETE FROM auth.users WHERE id = p_user_id;

  -- Return success
  RETURN jsonb_build_object(
      'success', true,
      'message', 'User berhasil dihapus dari sistem.'
  );

EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
        'success', false,
        'message', 'Gagal menghapus user: ' || SQLERRM
    );
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION public.admin_delete_auth_user(UUID) TO authenticated;
